version: "3.7"
services:
  # mongodb:
  #   image: mongo:6.0.6
  #   container_name: 'mongo'
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   healthcheck:
  #     test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   networks:
  #     - backend_services
  # order-service:
  #   image: ramymohamed/order-service-l8:latest
  #   container_name: 'order-service'
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   healthcheck:
  #     test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://order-service:3000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   environment:
  #     - AZURE_SERVICE_BUS_CONNECTION_STRING=${AZURE_SERVICE_BUS_CONNECTION_STRING}
  #     - AZURE_SERVICE_BUS_QUEUE_NAME=${AZURE_SERVICE_BUS_QUEUE_NAME}
  #   networks:
  #     - backend_services
  # makeline-service:
  #   image: ramymohamed/makeline-service-l8:latest
  #   container_name: 'makeline-service'
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   healthcheck:
  #     test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://makeline-service:3001/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   environment:
  #     - AZURE_SERVICE_BUS_CONNECTION_STRING=${AZURE_SERVICE_BUS_CONNECTION_STRING}
  #     - AZURE_SERVICE_BUS_QUEUE_NAME=${AZURE_SERVICE_BUS_QUEUE_NAME}
  #     - ORDER_DB_URI=${ORDER_DB_URI}
  #     - ORDER_DB_NAME=${ORDER_DB_NAME}
  #     - ORDER_DB_COLLECTION_NAME=${ORDER_DB_COLLECTION_NAME}
  #   networks:
  #     - backend_services
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy
  # virtual-customer:
  #   image: ramymohamed/virtual-customer-l8:latest
  #   container_name: 'virtual-customer'
  #   restart: always
  #   environment:
  #     - ORDER_SERVICE_URL=${ORDER_SERVICE_URL}
  #     - ORDERS_PER_HOUR=${ORDERS_PER_HOUR}
  #   networks:
  #     - backend_services
  #   depends_on:
  #     order-service:
  #       condition: service_healthy

  virtual-worker:
    image: congzhao0294/virtual-worker:latest  
    container_name: 'virtual-worker'
    restart: always
    env_file:
      - .env  
    networks:
      - backend_services  
    # depends_on:
    #   - makeline-service  


networks:
  backend_services:
    driver: bridge